### ISSUE TITLE
There aren’t any releases

### ISSUE THREAD

**Issue by lucascaton** [sonicwu/alfred-rgb2hex#1]
Hi there! 👋

The `README` says:

> You can download the workflow file from release folder.

But the [releases page](https://github.com/sonicwu/alfred-rgb2hex/releases) says:

> There aren’t any releases here

🙂

**Comment by sonicwu** [comment]
> Hi there! 👋
> 
> The `README` says:
> 
> > You can download the workflow file from release folder.
> 
> But the [releases page](https://github.com/sonicwu/alfred-rgb2hex/releases) says:
> 
> > There aren’t any releases here
> 
> 🙂

Sorry for late reply, the problem was I created this repo before Github shipped the new feature about the _releases page_.

Now this repo have already had two releases on the [Github releases page](https://github.com/sonicwu/alfred-rgb2hex/releases)
