### ISSUE TITLE
Feature request: support converting from hex to rgb

### ISSUE THREAD

**Issue by gnapse** [sonicwu/alfred-rgb2hex#6]
Would it be possible to support `#1BB6B7` as input, and have it output `rgb(27, 182, 183)`? The `#` prefix could be the clue to do this conversion in the opposite direction.

**Comment by sonicwu** [comment]
I think it's a common scenario, I'll start working on it.

**Comment by sonicwu** [comment]
This feature has been added into the version 2.1.0. 

Download the latest version from the release page or Packal and try it.

**Comment by gnapse** [comment]
It works like a charm. Thanks!
